// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "display_toggle", input: never, result: null },
    mutations: never,
    subscriptions: 
        { key: "bootstrap.pings", input: never, result: number }
};
