// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "auth.is_logged_in", input: never, result: boolean } | 
        { key: "auth.open_auth_window", input: never, result: null } | 
        { key: "bootstrap.show_main", input: never, result: null },
    mutations: 
        { key: "auth.sign_in", input: never, result: null } | 
        { key: "auth.sign_out", input: never, result: null } | 
        { key: "obs.preview.create", input: ObsPreviewCreation, result: number } | 
        { key: "obs.preview.destroy", input: number, result: null } | 
        { key: "obs.preview.set_pos", input: ObsPositionPayload, result: null } | 
        { key: "obs.preview.set_size", input: ObsSizePayload, result: null },
    subscriptions: 
        { key: "bootstrap.initialize", input: never, result: BootstrapStatus } | 
        { key: "game_detect.game_open", input: never, result: GameEvent }
};

/**
 * 
 */
export type ObsPreviewCreation = { window_label: string; x: number; y: number; width: number; height: number; background_color: number | null }

/**
 * 
 */
export type BootstrapStatus = { Error: string } | { Progress: [number, string] } | "Done"

/**
 * 
 */
export type ObsPositionPayload = { id: number; x: number; y: number }

/**
 * 
 */
export type ObsSizePayload = { id: number; width: number; height: number }

/**
 * 
 */
export type GameEvent = { Closed: WindowInfo } | { Opened: [WindowType, WindowInfo] }

/**
 * 
 */
export type WindowType = "Game" | "Window"

/**
 * Represents information about a window.
 */
export type WindowInfo = { full_exe: string; obs_id: string; pid: number; title: string | null; class: string | null; product_name: string | null; monitor: string | null; intersects: boolean | null; cmd_line: string | null; is_game: boolean }
